// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/blog/[slug].tsx";
import * as $2 from "./routes/blog/index.tsx";
import * as $3 from "./routes/github/[username].tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/projects.tsx";
import * as $6 from "./routes/search.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/MotionCard.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/blog/[slug].tsx": $1,
    "./routes/blog/index.tsx": $2,
    "./routes/github/[username].tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/projects.tsx": $5,
    "./routes/search.tsx": $6,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/MotionCard.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
